baseURL = 'https://kshatos.github.io/'
languageCode = 'en-us'

title = "Keagan Shatos"
author = "Keagan Shatos"
theme = "contrast-hugo"

[params]
  minimal = false
  excerpts = false
  description = "Keagan's Blog"
  math=true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10