baseURL = 'https://kshatos.github.io/'
languageCode = 'en-us'

title = "Keagan Shatos"
author = "Keagan Shatos"
theme = "contrast-hugo"

[markup.goldmark.renderer]
unsafe= true

[params]
  minimal = false
  excerpts = false
  description = "Keagan's Blog"
  math=true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
      identifier = "github"
      name = "Github"
      url = "https://github.com/kshatos/"
      weight = 10
      [menu.main.params]
        external = true

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
